namespace: spinnaker

resources:
- SpinnakerService.yml

# Apply the patches top down order
patchesStrategicMerge:
- profiles-patch.yml
- files-patch.yml
- service-settings-patch.yml
- config-patch.yml
