namespace: spinnaker

resources:
- SpinnakerService.yml

# Apply the patches top down order
patchesStrategicMerge:
- config-patch.yml
- profiles-patch.yml
- files-patch.yml
- service-settings-patch.yml
- patch-urls.yml
- patch-deck.yml
- ./auth/patch-basic-auth.yml
#- ./auth/patch-file-authz.yml
#- ./auth/patch-fiat-create-app-roles.yml
#- ./auth/patch-gate-tomcat-headers.yml
