apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  # spec.spinnakerConfig - This section is how to specify configuration spinnaker
  spinnakerConfig:
  # spec.spinnakerConfig.config - This section contains the contents of a deployment found in a halconfig .deploymentConfigurations[0]
    config:
      version: 2.24.0  # the version of Spinnaker to be deployed
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: spinnaker # Replace with the name of the S3 bucket created previously
          rootFolder: front50
          accessKeyId: minio         # (Optional, set only when using an IAM user to authenticate to the bucket instead of an IAM role)
          secretAccessKey: miniominio     # (Optional, set only when using an IAM user to authenticate to the bucket instead of an IAM role)
          pathStyleAccess: true
          endpoint: http://my-minio.minio.svc.cluster.local:9000

      armory:
        terraform:
          enabled: true

      features:
        artifacts: true
      artifacts:
        github:
          enabled: true
          accounts:
          - name: github
            token: encrypted:k8s!n:spin-secrets!k:github-token

      ci:
        travis:
          enabled: true
          masters:
          - name: ci
            baseUrl: https://travis-ci.com
            address: https://api.travis-ci.com
            githubToken: encrypted:k8s!n:spin-secrets!k:github-token
            permissions: {} 
          # regexes:
          # - /Upload https?:\/\/.+\/(.+\.(deb|rpm))/

